pipeline {
    agent any
    
    stages {
        
        stage('github-clone') {
            steps {
                git branch: 'main', credentialsId: 'Jenkins_Tokens', url: 'https://github.com/ssongjunu/movie-search-app.git'
            }
        }
        
   		// stage...
   	}
}
